[libraries]
duneuro=[FILL DUNEURO-PATH] # .../duneuro_installation/build-release/duneuro-py/src
duneuropt =[FILL DUNEURO-OPT-PATH] # .../duneuro-optimization/build/src
bb_path = [PATH TO THIS DIR]/Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs/branch_bound
master_thesis = [PATH TO THIS DIR]/Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs
[data_sphere]
tdcs_evaluation=/cap_data_exchange/sphere_mesh/tdcs_evaluation
cap_data_exchange=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange
current_densities=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/current_densities.h5
element_centers=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_centers.h5
element_labels=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_labels.h5
meshfile=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/small_sphere_mesh.npz
registered_sensors=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/registered_sensors.npz
outputdir_admm=./admm_results
outputdir_active_set=./active_set_results
outputdir_BB=./active_set_results

[data_head]
tdcs_evaluation=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation
cap_data_exchange=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange
current_densities=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/current_densities.h5
element_centers=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_centers.h5
element_labels=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_labels.h5
meshfile=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/small_sphere_mesh.npz
registered_sensors=[PATH_TO_EXCHANGE_DATA]/cap_data_exchange/sphere_mesh/registered_sensors.npz
# For the one single target that was examined deeply in the realistic head model experiments
single_radial_indice = [3199141]
single_radial_moment = [-0.521641,-0.226231,0.822624]
single_tangential_indice = [1699592]
single_tangential_moment = [0.40714,-0.67739,0.612683]
outputdir=./B_and_B_results
outputdir_BB=./B_and_B_results/realistic_head
outputdir_active_set= ./active_set_results