[libraries]
#duneuro=/home/dam-adam/MA/master_thesis/duneuro_installation/build-release/duneuro-py/src
duneuro=[FILL DUNEURO-PATH]
#duneuropt =/home/dam-adam/duneuro-optimization/build/src
duneuropt =[FILL DUNEURO-OPT-PATH]
#bb_path = .../Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs/branch_bound
bb_path = /home/dam-adam/Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs/branch_bound
#master_thesis = .../Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs
master_thesis = /home/dam-adam/Detailed-studies-of-numerical-methods-for-optimized-multi-channel-tdcs
[data_sphere]
tdcs_evaluation=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation
cap_data_exchange=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange
current_densities=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/current_densities.h5
element_centers=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_centers.h5
element_labels=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_labels.h5
meshfile=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/small_sphere_mesh.npz
registered_sensors=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/registered_sensors.npz
outputdir_admm=./admm_results
outputdir_active_set=./active_set_results
outputdir_BB=./active_set_results

[data_head]
tdcs_evaluation=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation
cap_data_exchange=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange
current_densities=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/current_densities.h5
element_centers=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_centers.h5
element_labels=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/tdcs_evaluation/element_labels.h5
meshfile=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/small_sphere_mesh.npz
registered_sensors=/home/dam-adam/MA/cap_data_exchange/cap_data_exchange/sphere_mesh/registered_sensors.npz
# For the one single target that was examined deeply in the realistic head model experiments
single_radial_indice = [3199141]
single_radial_moment = [-0.521641,-0.226231,0.822624]
single_tangential_indice = [1699592]
single_tangential_moment = [0.40714,-0.67739,0.612683]
outputdir_active_set=./active_set_results